dataset:
  train:
    path: /home/cvip/jun/kidnap/dataset/fps2_512/train
    batch_size: 32
    shuffle: True
    drop_last: True
    preprocess:
      - type: horizontal
      - type: tensor


  test:
    path : /home/cvip/jun/kidnap/dataset/fps2_512/test
    batch_size: 32
    preprocess:
      - type: tensor